### ISSUE TITLE
Null Conditional Operator causes SA1009 to trigger

### ISSUE THREAD

**Issue by GregReddick** [ptittof57/Visual-StyleCop#11]
The new Null Conditional Operator in C# version 6 causes SA1000 to trigger in some circumstances.

I have this code:

internal static class AssemblyInfo
{
	internal static T Attribute<T>() where T : Attribute
	{
		return typeof(AssemblyInfo).Assembly.GetCustomAttribute<T>();
	}
}

And this call:

string company = AssemblyInfo.Attribute<AssemblyCompanyAttribute>()?.Company;

The call causes SA1009 CSharp.Spacing : Invalid spacing around the closing parenthesis

However in this case, a ? here is properly spaced.

**Comment by ptittof57** [comment]
Already fixed in #9.
