### ISSUE TITLE
Does not appear to work in VS 2013 unless VS 2015 is also installed.

### ISSUE THREAD

**Issue by streamtree** [ptittof57/Visual-StyleCop#3]
Attempting to use in VS 2013 on a computer where VS 2015 is not also installed generates an error:

  <entry>
    <record>1553</record>
    <time>2015/08/26 19:14:49.273</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [StyleCop.VisualStudio.StyleCopVSPackage, StyleCop.VSPackage, Version=4.7.0.0, Culture=neutral, PublicKeyToken=f904653c63bc2738]</description>
    <guid>{629EB7CC-69C2-43AC-9BC9-482B0F810C4E}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>

**Comment by ptittof57** [comment]
hi, @streamtree 

Thanks to report this issue, it will be fixed in next release 4.7.53 !

I have added missing dll in package, but with next version you must install [framework 4.6](https://www.microsoft.com/fr-fr/download/details.aspx?id=48130) to use it for VS2013.

**Comment by ptittof57** [comment]
hi @streamtree the release 4.7.53 is available, let me know if you have any issue to use it on VS2013.
