### ISSUE TITLE
Consider joining StyleCopAnalyzers

### ISSUE THREAD

**Issue by sharwell** [ptittof57/Visual-StyleCop#5]
Hi @ptittof57,

I'd like to invite you to join the [DotNetAnalyzers/StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) project. Over the past 9 months, more than 20 community members have joined together to build a faithful reproduction of StyleCop using the .NET Compiler Platform (Roslyn). The project implements the nearly all of the original StyleCop rules and even includes code fixes for most of them, all without requiring any special tools or Visual Studio extensions. We have over 5000 unit tests (including coverage of C# 6 features), a [live status page](http://stylecop.pdelvo.com/), and an [active discussion room on Gitter](https://gitter.im/DotNetAnalyzers/StyleCopAnalyzers?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

If you don't join us, please consider at least joining our chat room to discuss ways to make sure our diagnostic IDs stay in sync over time. :smile:

**Comment by ptittof57** [comment]
Hi @sharwell,

I saw your project and I can say that it is a great and powerfull tool, more than previous stylecop version. 
I want just provides a quick win solution based on previous code without any changes for end user. 
So no problem for me to stay sync over the time.

Christophe.
