### ISSUE TITLE
Several C# 6.0 features still aren't supported

### ISSUE THREAD

**Issue by GuMiner** [ptittof57/Visual-StyleCop#7]
Hello @ptittof57,

I've been testing the functionality of this project at work, and have found a few C# 6.0 language features that still cause a syntax exception:
*Index Initializers*: 
```csharp
Dictionary<int, string> myDictionary = new Dictionary<int, string>()
{
    [1] = "One"
};
```
*Exception Filters*:
```csharp
try
{
}
catch (Exception) when (true)
{
}
```
*Expression-bodied function members / parameters*
```csharp
public string Test => "Test";
public string Test(string a) => a + "b";
```
*Using static*
```csharp
using static System.Console;
```

I'm using version 4.7.52 on VS 2015 Enterprise.
Thanks for the work you have done to this project so far!

--Gustave Granroth.
Software Engineer, gugra@microsoft.com

**Comment by ptittof57** [comment]
Hi Gustave,

Thanks for your feedback.

I was writting the new specifications when you posted this issue :)
Now it's done, I must write unit tests and I try to release before the end of the week.

Please see below some expressions supported in next release 4.7.53 :

Index Initializers :

![dictionaryinit](https://cloud.githubusercontent.com/assets/10358735/9552774/d8569dbc-4dba-11e5-9395-cf95b4e7b7fb.PNG)

Expression Bodied :

![expressionbodied](https://cloud.githubusercontent.com/assets/10358735/9552805/120c761c-4dbb-11e5-90a9-17ef3c255f6c.PNG)

Using Static :

![usingstatic](https://cloud.githubusercontent.com/assets/10358735/9552818/2a99038a-4dbb-11e5-83a3-b4312b6bb99a.PNG)

Exception Filters:

![exceptionsfilter](https://cloud.githubusercontent.com/assets/10358735/9552841/4a1af100-4dbb-11e5-9a15-a383734ab810.PNG)

Christophe.

**Comment by ptittof57** [comment]
Hi, @GuMiner the release 4.7.53 is available, let me know if you have any issue with C# 6.0 features.
