### ISSUE TITLE
SA0102 false positive

### ISSUE THREAD

**Issue by elyoh** [ptittof57/Visual-StyleCop#9]
The following line:
```C#
var when = new XElement("someelement");
```
incorrectly gives:
SA0102 : CSharp.CsParser : A syntax error has been discovered in file ... .	

Changing when to another name fixes the issue.
 
Build 4.7.53

**Comment by ptittof57** [comment]
I have added the when keyword used by exception without any check if it was a variable declaration.
FITNR.
